version: 2
jobs:
  "node-6":
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    environment:
      - CIRCLE_TAG: "v1.6.1"

    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: "docker build -t expressgateway/express-gateway:${CIRCLE_TAG} --build-arg VERSION=latest ."
      - run: "docker build -t expressgateway/express-gateway:${CIRCLE_TAG}-getting-started --build-arg VERSION=latest --build-arg TYPE=getting-started ."
      - run: "docker tag expressgateway/express-gateway:${CIRCLE_TAG} expressgateway/express-gateway:latest"
      - run: "docker tag expressgateway/express-gateway:${CIRCLE_TAG}-getting-started expressgateway/express-gateway:latest-getting-started"

workflows:
  version: 2
  build:
    jobs:
      - node-6:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
